"""initial schema: tables, row-level security, audit immutability, lookup functions, grants

Revision ID: 0001
Revises: (none)
Create Date: 2026-09-30 04:01:56.709355
"""

import os
import re

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

APP_ROLE = os.environ.get("PP_APP_DB_ROLE", "payeeproof_app")
if not re.fullmatch(r"[a-z_][a-z0-9_]{0,62}", APP_ROLE):
    raise RuntimeError("PP_APP_DB_ROLE must be a simple lower-case identifier")

TENANT_TABLES = [
    "invitations",
    "api_keys",
    "vendors",
    "vendor_bank_accounts",
    "change_requests",
    "verifications",
    "attestations",
    "approvals",
    "screening_runs",
    "screening_entries",
    "flagged_accounts",
    "audit_events",
    "control_reviews",
]
APPEND_ONLY_TABLES = ["audit_events", "security_events"]

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("status", sa.String(length=10), server_default="queued", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_status_run_at", "jobs", ["status", "run_at"], unique=False)
    op.create_table(
        "network_contributions",
        sa.Column("network_fp", sa.String(length=64), nullable=False),
        sa.Column("org_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("network_fp", "org_hash", "kind"),
    )
    op.create_table(
        "network_reputation",
        sa.Column("network_fp", sa.String(length=64), nullable=False),
        sa.Column("verified_orgs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("flagged_orgs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("network_fp"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column("plan_interval", sa.String(length=10), nullable=True),
        sa.Column("subscription_status", sa.String(length=30), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=100), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=100), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("past_due_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("nacha_settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("network_participation", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "security_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("event", sa.String(length=60), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret_enc", sa.Text(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=True),
        sa.Column("recovery_codes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("failed_logins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mfa_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prefix"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "subject_type", "subject_id", "user_id", name="uq_approval_once"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=10), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("actor_label", sa.String(length=320), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "seq", name="uq_audit_org_seq"),
    )
    op.create_table(
        "control_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("settings_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flagged_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("account_fp", sa.String(length=64), nullable=False),
        sa.Column("account_last4", sa.String(length=4), nullable=False),
        sa.Column("routing_number", sa.String(length=9), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_flagged_org_fp", "flagged_accounts", ["org_id", "account_fp"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_membership_org_user"),
    )
    op.create_table(
        "password_resets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "screening_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("entry_count", sa.Integer(), nullable=False),
        sa.Column("total_credit_cents", sa.BigInteger(), nullable=False),
        sa.Column("total_debit_cents", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("rule_counts", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("integrity_issues", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("required_approvals", sa.Integer(), server_default="1", nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by", sa.UUID(), nullable=True),
        sa.Column("certificate_sha256", sa.String(length=64), nullable=True),
        sa.Column("certificate", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["released_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_runs_org_created", "screening_runs", ["org_id", "created_at"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("mfa_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=True),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("contact_updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vendors_org_name", "vendors", ["org_id", "name"], unique=False)
    op.create_table(
        "change_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("proposed_routing", sa.String(length=9), nullable=True),
        sa.Column("proposed_account_enc", sa.Text(), nullable=True),
        sa.Column("proposed_account_fp", sa.String(length=64), nullable=True),
        sa.Column("proposed_account_last4", sa.String(length=4), nullable=True),
        sa.Column("proposed_account_type", sa.String(length=10), nullable=True),
        sa.Column("proposed_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("request_notes", sa.Text(), nullable=True),
        sa.Column("untrusted_contact_in_request", sa.String(length=300), nullable=True),
        sa.Column("known_phone_snapshot", sa.String(length=32), nullable=True),
        sa.Column("known_email_snapshot", sa.String(length=320), nullable=True),
        sa.Column("known_contact_age_days", sa.Integer(), nullable=True),
        sa.Column("risk_flags", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cr_org_status", "change_requests", ["org_id", "status"], unique=False)
    op.create_table(
        "screening_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("entry_index", sa.Integer(), nullable=False),
        sa.Column("batch_number", sa.Integer(), nullable=False),
        sa.Column("sec_code", sa.String(length=3), nullable=False),
        sa.Column("transaction_code", sa.String(length=2), nullable=False),
        sa.Column("routing", sa.String(length=9), nullable=False),
        sa.Column("account_fp", sa.String(length=64), nullable=False),
        sa.Column("account_last4", sa.String(length=4), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("receiver_name", sa.String(length=64), nullable=False),
        sa.Column("individual_id", sa.String(length=32), nullable=False),
        sa.Column("trace_number", sa.String(length=15), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("bank_account_id", sa.UUID(), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["screening_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_entries_org_fp", "screening_entries", ["org_id", "account_fp"], unique=False)
    op.create_index("ix_entries_run", "screening_entries", ["run_id", "entry_index"], unique=False)
    op.create_table(
        "vendor_bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("routing_number", sa.String(length=9), nullable=False),
        sa.Column("account_enc", sa.Text(), nullable=False),
        sa.Column("account_fp", sa.String(length=64), nullable=False),
        sa.Column("account_last4", sa.String(length=4), nullable=False),
        sa.Column("account_type", sa.String(length=10), server_default="checking", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vba_org_fp", "vendor_bank_accounts", ["org_id", "account_fp"], unique=False)
    op.create_table(
        "attestations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("sent_to_email", sa.String(length=320), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response", sa.String(length=20), nullable=True),
        sa.Column("responder_name", sa.String(length=200), nullable=True),
        sa.Column("responder_ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["change_request_id"], ["change_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "verifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("performed_by", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["change_request_id"], ["change_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["performed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    _security_upgrade()


def downgrade() -> None:
    _security_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verifications")
    op.drop_table("attestations")
    op.drop_index("ix_vba_org_fp", table_name="vendor_bank_accounts")
    op.drop_table("vendor_bank_accounts")
    op.drop_index("ix_entries_run", table_name="screening_entries")
    op.drop_index("ix_entries_org_fp", table_name="screening_entries")
    op.drop_table("screening_entries")
    op.drop_index("ix_cr_org_status", table_name="change_requests")
    op.drop_table("change_requests")
    op.drop_index("ix_vendors_org_name", table_name="vendors")
    op.drop_table("vendors")
    op.drop_table("sessions")
    op.drop_index("ix_runs_org_created", table_name="screening_runs")
    op.drop_table("screening_runs")
    op.drop_table("password_resets")
    op.drop_table("memberships")
    op.drop_table("invitations")
    op.drop_index("ix_flagged_org_fp", table_name="flagged_accounts")
    op.drop_table("flagged_accounts")
    op.drop_table("control_reviews")
    op.drop_table("audit_events")
    op.drop_table("approvals")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("stripe_events")
    op.drop_table("security_events")
    op.drop_table("organizations")
    op.drop_table("network_reputation")
    op.drop_table("network_contributions")
    op.drop_index("ix_jobs_status_run_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS pp_append_only()")
    op.execute("DROP FUNCTION IF EXISTS pp_current_org()")
    op.execute("DROP FUNCTION IF EXISTS pp_current_user()")


def _security_upgrade() -> None:
    op.execute("""
    CREATE FUNCTION pp_current_org() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT NULLIF(current_setting('app.org_id', true), '')::uuid $$;
    CREATE FUNCTION pp_current_user() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;
    """)
    for t in TENANT_TABLES:
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {t} USING (org_id = pp_current_org()) "
            f"WITH CHECK (org_id = pp_current_org())"
        )
    op.execute("ALTER TABLE memberships ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY membership_access ON memberships "
        "USING (org_id = pp_current_org() OR user_id = pp_current_user()) "
        "WITH CHECK (org_id = pp_current_org())"
    )
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY org_access ON organizations "
        "USING (id = pp_current_org() OR id IN (SELECT m.org_id FROM memberships m "
        "WHERE m.user_id = pp_current_user())) WITH CHECK (id = pp_current_org())"
    )

    # Audit log is append-only, even for the schema owner (triggers fire for owners too).
    op.execute("""
    CREATE FUNCTION pp_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege'; END $$;
    """)
    for t in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {t}_no_mutation BEFORE UPDATE OR DELETE ON {t} "
            f"FOR EACH ROW EXECUTE FUNCTION pp_append_only()"
        )
        op.execute(
            f"CREATE TRIGGER {t}_no_truncate BEFORE TRUNCATE ON {t} "
            f"FOR EACH STATEMENT EXECUTE FUNCTION pp_append_only()"
        )

    # Narrow cross-tenant lookups needed before a tenant context exists. SECURITY DEFINER
    # functions run as the table owner (who is not subject to RLS) and return only the
    # minimum columns for one exact-match key.
    op.execute("""
    CREATE FUNCTION pp_lookup_api_key(p_prefix text)
      RETURNS TABLE(id uuid, org_id uuid, key_hash text, scopes text[], revoked_at timestamptz)
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT k.id, k.org_id, k.key_hash::text, k.scopes::text[], k.revoked_at FROM api_keys k
         WHERE k.prefix = p_prefix $$;
    CREATE FUNCTION pp_lookup_invitation(p_token_hash text)
      RETURNS TABLE(id uuid, org_id uuid)
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT i.id, i.org_id FROM invitations i WHERE i.token_hash = p_token_hash
         AND i.accepted_at IS NULL AND i.expires_at > now() $$;
    CREATE FUNCTION pp_lookup_attestation(p_token_hash text)
      RETURNS TABLE(id uuid, org_id uuid)
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT a.id, a.org_id FROM attestations a WHERE a.token_hash = p_token_hash $$;
    CREATE FUNCTION pp_org_for_stripe_customer(p_customer text)
      RETURNS uuid
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT o.id FROM organizations o WHERE o.stripe_customer_id = p_customer $$;
    CREATE FUNCTION pp_orgs_with_stale_changes(p_cutoff timestamptz)
      RETURNS TABLE(org_id uuid, stale_count bigint)
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT c.org_id, count(*) FROM change_requests c
         WHERE c.status IN ('pending_verification', 'verified') AND c.created_at < p_cutoff
         GROUP BY c.org_id $$;
    CREATE FUNCTION pp_org_exists(p_org uuid)
      RETURNS boolean
      LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
      $$ SELECT EXISTS (SELECT 1 FROM organizations o WHERE o.id = p_org) $$;
    """)
    fns = [
        "pp_lookup_api_key(text)",
        "pp_lookup_invitation(text)",
        "pp_lookup_attestation(text)",
        "pp_org_for_stripe_customer(text)",
        "pp_org_exists(uuid)",
        "pp_orgs_with_stale_changes(timestamptz)",
        "pp_current_org()",
        "pp_current_user()",
    ]
    for fn in fns:
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {fn} TO {APP_ROLE}")

    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")
    rw = [
        "organizations",
        "users",
        "memberships",
        "sessions",
        "password_resets",
        "jobs",
        "stripe_events",
        "network_reputation",
        "network_contributions",
        *[t for t in TENANT_TABLES if t != "audit_events"],
    ]
    for t in rw:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO {APP_ROLE}")
    for t in APPEND_ONLY_TABLES:
        op.execute(f"GRANT SELECT, INSERT ON {t} TO {APP_ROLE}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}")
    op.execute(f"GRANT SELECT ON alembic_version TO {APP_ROLE}")


def _security_downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS org_access ON organizations")
    for fn in [
        "pp_lookup_api_key(text)",
        "pp_lookup_invitation(text)",
        "pp_lookup_attestation(text)",
        "pp_org_for_stripe_customer(text)",
        "pp_org_exists(uuid)",
        "pp_orgs_with_stale_changes(timestamptz)",
    ]:
        op.execute(f"DROP FUNCTION IF EXISTS {fn}")
    for t in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_no_mutation ON {t}")
        op.execute(f"DROP TRIGGER IF EXISTS {t}_no_truncate ON {t}")
